spring.application.name=ems-backend-postgre
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=root
spring.datasource.password=Sagar@123

spring.jpa.hibernate.ddl-auto=update
